// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/protobufmessage/hello/hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// To compile run: protoc --go_out=. ./examples/protobufmessage/hello/hello.proto
type Message struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_17503a1d2b9a6102, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ActivityMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityMessage) Reset()         { *m = ActivityMessage{} }
func (m *ActivityMessage) String() string { return proto.CompactTextString(m) }
func (*ActivityMessage) ProtoMessage()    {}
func (*ActivityMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_17503a1d2b9a6102, []int{1}
}

func (m *ActivityMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityMessage.Unmarshal(m, b)
}
func (m *ActivityMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityMessage.Marshal(b, m, deterministic)
}
func (m *ActivityMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityMessage.Merge(m, src)
}
func (m *ActivityMessage) XXX_Size() int {
	return xxx_messageInfo_ActivityMessage.Size(m)
}
func (m *ActivityMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityMessage proto.InternalMessageInfo

func (m *ActivityMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "hello.Message")
	proto.RegisterType((*ActivityMessage)(nil), "hello.ActivityMessage")
}

func init() {
	proto.RegisterFile("examples/protobufmessage/hello/hello.proto", fileDescriptor_17503a1d2b9a6102)
}

var fileDescriptor_17503a1d2b9a6102 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4a, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xcb, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0x87, 0x90, 0x7a, 0x60, 0x39, 0x21,
	0x56, 0x30, 0x47, 0x49, 0x9a, 0x8b, 0xdd, 0x17, 0xa2, 0x46, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38,
	0x5d, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x54, 0x52, 0xe6, 0xe2, 0x77, 0x4c, 0x2e,
	0xc9, 0x2c, 0xcb, 0x2c, 0xa9, 0xc4, 0xa9, 0x28, 0x89, 0x0d, 0x6c, 0x9e, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x21, 0x7f, 0x23, 0xa8, 0x7d, 0x00, 0x00, 0x00,
}
